# 03 OnlineQuiz - Algoritmos Genéticos - Simulated Annealing


# Ejercicio 1:

### <font style="color:red">1.A) Realiza una función que produzca una población inicial de soluciones de un cierto problema para resolverlo por medio de algoritmos genéticos o simulated annealing de forma que, cada solución:

- Está representada por un vector de 10 elements con valores entre 0 y 99, ambos incluidos.
- Cada vector tiene al menos dos números iguales

Salida esperada (vectores aleatorios):

    [99 99 11 71 55 54 71  1 57 23] valores repetidos 2
    [21 32 96 83 34 92 23 43 70 21] valores repetidos 1
    [37  0 73 15 15 96  8  1 84 36] valores repetidos 1
    [44 27 27 21  6 30 17 90  9 31] valores repetidos 1
    [85 51 19 43 16 93 93 68 19 15] valores repetidos 2
    [82 59 97 21 94 28  6 95 95 83] valores repetidos 1
    [26  9  9 13 59 30 55 48 67  0] valores repetidos 1
    [83 27 19 19 95 90 41 81 46 89] valores repetidos 1
    [97 29 79 38 57 71 61 65 78 78] valores repetidos 1
    [70  6 21 15 73 15 83 11 28 28] valores repetidos 2
    [28 59 57  8 27 84 13 13 89 54] valores repetidos 1
    [84 82 91 95 84 16 67 67 88 67] valores repetidos 3
    [62 54 33 33  3 63 56 80 50 57] valores repetidos 1
    [91  3 37 37 89 37 40 14 53 33] valores repetidos 2
    [33 83 73  1 71 78  8  7 86 86] valores repetidos 1

In [1]:
import numpy as np

def init_population(n):
    r = np.random.randint(100, size=(n,10))
    ## TU CODIGO AQUI
    for i in range (n):
        t = np.random.randint(11)
        r[i,t-1] = r[i,t-2] 
        
    return r

### 1.B) inspecciona el resultado de tu código

In [2]:
r = init_population(15)
for i in range(len(r)):
    print r[i], "valores repetidos", 10-len(np.unique(r[i]))

[ 2 55 56 77  3 94 94  4 48 74] valores repetidos 1
[ 2 51 19 76 99 50 22 48 40  2] valores repetidos 1
[19 17 85 86 14  0 39 39 57 34] valores repetidos 1
[35 28 39 18 39 16 30  2  2 60] valores repetidos 2
[12 31 26 46 56  3 56 51 41 41] valores repetidos 2
[94 94 41 59 28 44 11 59 93 37] valores repetidos 2
[46  5  5 82 45 76 71 11 75 85] valores repetidos 1
[26 80 59 31  1 59  6 10 67 67] valores repetidos 2
[31 31 56 99 39 67 64  5 42 17] valores repetidos 1
[67 29 72  0 50 50 89 99 95  3] valores repetidos 1
[53 63 72 46 13 13 75 65 93 93] valores repetidos 2
[21 21 58 82 54 45 21  3 57 52] valores repetidos 2
[72 67 50 95 96 61 53 30 27 27] valores repetidos 1
[15 88 88 57 31 90 57 72 60 36] valores repetidos 2
[66 57 20 76 65 65 41 43 10 86] valores repetidos 1


### 1.C) verifica que el ejercicio está correcto


In [3]:
r = init_population(200)
print "Todos los individuos tienen al menos 2 números iguales ::", np.all([len(np.unique(r[i]))<=9 for i in xrange(len(r))])

Todos los individuos tienen al menos 2 números iguales :: True


# Ejercicio 2:

### <font style="color:red">1.A) Realiza una función que produzca una mutación en un vector de enteros:

Tenemos un vector $x$ con 10 elementos que son números enteros entre 0 y 9. Es decir $x =  [x_0, x_1,...x_i, ... x_9]$ con $x_i \in [0,..,9]$

implementa una función que mute un vector con una probabilidad $p$ dada. Por ejemplo, si $p=0.7$ el 30% de las veces que se llama la función devuelve el mismo $x$ sin modificarlo pero el 70% devuelve el vector original mutado.

para hacer una mutación:

1. Selecciona una posición aleatoria en el vector
2. Cambia el valor del elemento en la posición seleccionada

Salida esperada (es aleatoria, tu salida no será igual):

    x
    [0 8 7 6 5 8 6 3 7 3]
    mutations
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 8 6 6 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 1 6 3 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [9 8 7 6 5 8 6 3 7 3]


In [4]:
import numpy as np

def simple_mutate(x, prob):
    
    r = np.copy(x)

    if  np.random.random() < prob:
        h = np.random.randint(len(r))
        r[h] = r [h+1] if h == 10 else r[0]
    ## TU CODIGO AQUI
           
    return r
    

### 1.B) inspecciona el resultado de tu código

In [5]:
x = np.random.randint(10, size=10)
print "x\n",x
print "mutations"
for i in range(10):
    print simple_mutate(x, 0.1)

x
[5 3 3 9 8 3 0 8 7 5]
mutations
[5 3 3 9 8 3 0 8 7 5]
[5 3 3 9 8 3 0 8 7 5]
[5 3 3 9 8 3 0 8 7 5]
[5 3 3 9 8 5 0 8 7 5]
[5 3 3 9 8 3 0 8 7 5]
[5 3 3 9 8 3 0 8 7 5]
[5 3 3 9 8 3 0 8 7 5]
[5 3 3 9 8 3 0 8 7 5]
[5 3 3 9 8 3 0 8 7 5]
[5 3 3 9 8 3 0 8 7 5]


### 1.C) verifica que el ejercicio está correcto

In [6]:
x = np.random.randint(10, size=100)
N=1000
pct_muts_50 = sum([sum(simple_mutate(x, 0.5) != x) for i in xrange(N)])*1./N
pct_muts_10 = sum([sum(simple_mutate(x, 0.1) != x) for i in xrange(N)])*1./N
print "Testing mutation probability 0.5", np.allclose(pct_muts_50, 0.5, atol=0.1)
print "Testing mutation probability 0.1", np.allclose(pct_muts_10, 0.1, atol=0.1)
print "Testing solutions valid         ", np.all([np.all(simple_mutate(x, 0.5) < 10) for i in xrange(N)])
print "Testing solutions valid         ", np.all([np.all(simple_mutate(x, 0.5) >= 0) for i in xrange(N)])

Testing mutation probability 0.5 True
Testing mutation probability 0.1 True
Testing solutions valid          True
Testing solutions valid          True


# Ejercicio 3:

### <font style="color:red">1.A) Realiza una función que dados dos vectores $v_1$ y $v_2$, produzca un nuevo vector $r$ de forma que:

- selecciona una posición aleatoria de $r$
- `r[pos:] = v1[pos:]`, donde $pos$ es la posición seleccionada en el punto anterior
- `r[:pos] = v2[:pos]`

Salida esperada (vectores aleatorios):


    v1 [85 55  9 24 71 80 94 26 36 24]
    v2 [90  8 63 74 71 55 44 84 61 27]
    r  [ 0 55  9 24 71 80 94 26 36 24]


In [7]:
def crossover(v1, v2):
    
    r = np.zeros(len(v1)).astype(int)
    k = np.random.randint(len(r))
    r[k:] = v1[k:]
    r[:k] = v2[:k]
    
    ## TU CODIGO AQUI
    return r
    

### 1.B) inspecciona el resultado de tu código

In [8]:
v1 = np.random.randint(100, size=10)
v2 = np.random.randint(100, size=10)
r = crossover(v1,v2)
print "v1", v1
print "v2", v2
print "r ", r

v1 [14 27 21 44 23 77  2 92  8 51]
v2 [34 22 71 75 68  0 83 98 33 85]
r  [14 27 21 44 23 77  2 92  8 51]


### 1.C) verifica que el ejercicio está correcto

In [9]:
c = []
for i in range(100):
    v1 = np.random.randint(100, size=10)
    v2 = np.random.randint(100, size=10)
    r = crossover(v1,v2)
    tf = np.all(np.unique(list(np.where(v2==r)[0]) + list(np.where(v1==r)[0]))==np.arange(10))
    if not tf:
        print "--"
        print "v1", v1
        print "v2", v2
        print "r ", r
        print "l ", np.unique(list(np.where(v2==r)[0]) + list(np.where(v1==r)[0])), tf
    c.append(tf)
    
print "cross over correctos :: ", np.all(c)

cross over correctos ::  True


# Ejercicio 4:

### <font style="color:red">1.A) Realiza una función que dado un vector $x$, con 10 elementos enteros, entre 0 y 99 ambos incluidos, genere un nuevo vector $r$ de forma que la distancia euclideana entre ambos sea 2:

- selecciona una posición aleatoria de $r$
- `r[pos:] = v1[pos:]`, donde $pos$ es la posición seleccionada en el punto anterior
- `r[:pos] = v2[:pos]`

Salida esperada (vectores aleatorios):


    v1 [85 55  9 24 71 80 94 26 36 24]
    v2 [90  8 63 74 71 55 44 84 61 27]
    r  [ 0 55  9 24 71 80 94 26 36 24]


In [10]:
import numpy as np

def vecino(x):
    
    r = np.copy(x)
    k = np.random.randint(len(r))
    r[k]= r[k] -2
    
    ## TU CODIGO AQUI
    return r

### 1.B) inspecciona el resultado de tu código

In [11]:
x = np.random.randint(10, size=10)
r = vecino(x)
print "x", x
print "r", r
print "distnacia euclideana", np.sqrt(np.sum((x-r)**2))

x [4 8 1 6 2 1 8 0 6 0]
r [4 6 1 6 2 1 8 0 6 0]
distnacia euclideana 2.0


### 1.C) verifica que el ejercicio está correcto

In [12]:
distancias = []
for i in xrange(100):
    x = np.random.randint(10, size=10)
    r = vecino(x)
    distancias.append(np.sqrt(np.sum((x-r)**2)))
    
print "todas las distancias son 2 ::", np.allclose(distancias, 2)

todas las distancias son 2 :: True
