# 03 OnlineQuiz - Algoritmos Genéticos - Simulated Annealing


# Ejercicio 1:

### <font style="color:red">1.A) Realiza una función que produzca una población inicial de soluciones de un cierto problema para resolverlo por medio de algoritmos genéticos o simulated annealing de forma que, cada solución:

- Está representada por un vector de 10 elements con valores entre 0 y 99, ambos incluidos.
- Cada vector tiene al menos dos números iguales

Salida esperada (vectores aleatorios):

    [99 99 11 71 55 54 71  1 57 23] valores repetidos 2
    [21 32 96 83 34 92 23 43 70 21] valores repetidos 1
    [37  0 73 15 15 96  8  1 84 36] valores repetidos 1
    [44 27 27 21  6 30 17 90  9 31] valores repetidos 1
    [85 51 19 43 16 93 93 68 19 15] valores repetidos 2
    [82 59 97 21 94 28  6 95 95 83] valores repetidos 1
    [26  9  9 13 59 30 55 48 67  0] valores repetidos 1
    [83 27 19 19 95 90 41 81 46 89] valores repetidos 1
    [97 29 79 38 57 71 61 65 78 78] valores repetidos 1
    [70  6 21 15 73 15 83 11 28 28] valores repetidos 2
    [28 59 57  8 27 84 13 13 89 54] valores repetidos 1
    [84 82 91 95 84 16 67 67 88 67] valores repetidos 3
    [62 54 33 33  3 63 56 80 50 57] valores repetidos 1
    [91  3 37 37 89 37 40 14 53 33] valores repetidos 2
    [33 83 73  1 71 78  8  7 86 86] valores repetidos 1

In [1]:
import numpy as np

def init_population(n):
    r = np.random.randint(100, size=(n,10))
    ## TU CODIGO AQUI
    for i in range(n):
        i1=np.random.randint(10)
        i2=i1+1 if i1<9 else 0
        j1=np.random.randint (10)
        j2=j1+1 if j1<9 else 0
        r[i][i1]=r[i][i2]
        r[i][j1]=r[i][j2]

    
    
    return r

### 1.B) inspecciona el resultado de tu código

In [2]:
r = init_population(15)
for i in range(len(r)):
    print r[i], "valores repetidos", 10-len(np.unique(r[i]))

[10 44 29 11 51  4  4 34 34 37] valores repetidos 2
[67 67 59 59 58 19 10 78 75 50] valores repetidos 2
[ 2 99 49 12 12 12 27 55 82  5] valores repetidos 2
[13 13  6 53 78 40 38 41 67 13] valores repetidos 2
[ 5  5 66 65 33 46 46  6 73 38] valores repetidos 2
[31 79 46 46 80 80 50 78 66 71] valores repetidos 2
[68 46 90 29 73  5  5 10 81 68] valores repetidos 2
[82 82 57 35 38 64 40 70 79 82] valores repetidos 2
[95 53 53 93 15 40 18  2 53 95] valores repetidos 3
[20 40 31 22 22 24 60 58 45 20] valores repetidos 2
[60  1 61  9 63 63 34 32 72 89] valores repetidos 1
[80 37 44 51 10 10 45 97 73 14] valores repetidos 1
[79 79 88 11 24 30 36 32 61 51] valores repetidos 1
[25 18 18 52 24 90 90 66 74 14] valores repetidos 2
[74 73 89 20 16 16 98 26 26 52] valores repetidos 2


### 1.C) verifica que el ejercicio está correcto


In [3]:
r = init_population(200)
print "Todos los individuos tienen al menos 2 números iguales ::", np.all([len(np.unique(r[i]))<=9 for i in xrange(len(r))])

Todos los individuos tienen al menos 2 números iguales :: True


# Ejercicio 2:

### <font style="color:red">1.A) Realiza una función que produzca una mutación en un vector de enteros:

Tenemos un vector $x$ con 10 elementos que son números enteros entre 0 y 9. Es decir $x =  [x_0, x_1,...x_i, ... x_9]$ con $x_i \in [0,..,9]$

implementa una función que mute un vector con una probabilidad $p$ dada. Por ejemplo, si $p=0.7$ el 30% de las veces que se llama la función devuelve el mismo $x$ sin modificarlo pero el 70% devuelve el vector original mutado.

para hacer una mutación:

1. Selecciona una posición aleatoria en el vector
2. Cambia el valor del elemento en la posición seleccionada

Salida esperada (es aleatoria, tu salida no será igual):

    x
    [0 8 7 6 5 8 6 3 7 3]
    mutations
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 8 6 6 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 1 6 3 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [0 8 7 6 5 8 6 3 7 3]
    [9 8 7 6 5 8 6 3 7 3]


In [4]:
import numpy as np

def simple_mutate(x, prob):
    
    r = np.copy(x)
    ## TU CODIGO AQUI
    if(np.random.random()<prob):
        i=np.random.randint(len(x))
        r[i]=r[i]+1 if((r[i]+1)<10) else r[i]-1
           
    return r
    

### 1.B) inspecciona el resultado de tu código

In [5]:
x = np.random.randint(10, size=10)
print "x\n",x
print "mutations"
for i in range(10):
    print simple_mutate(x, 0.5)

x
[7 0 0 8 2 3 1 1 1 6]
mutations
[7 0 0 8 2 3 2 1 1 6]
[7 0 0 8 2 3 1 1 1 6]
[7 0 1 8 2 3 1 1 1 6]
[7 0 0 8 2 4 1 1 1 6]
[7 0 0 8 2 3 1 1 2 6]
[7 0 0 8 2 3 1 1 1 6]
[7 0 0 8 2 3 1 1 1 7]
[7 0 0 8 2 3 1 1 1 6]
[7 0 0 8 2 3 1 1 1 6]
[7 0 0 8 2 4 1 1 1 6]


### 1.C) verifica que el ejercicio está correcto

In [6]:
x = np.random.randint(10, size=100)
N=1000
pct_muts_50 = sum([sum(simple_mutate(x, 0.5) != x) for i in xrange(N)])*1./N
pct_muts_10 = sum([sum(simple_mutate(x, 0.1) != x) for i in xrange(N)])*1./N

print "Testing mutation probability 0.5", np.allclose(pct_muts_50, 0.5, atol=0.1)
print "Testing mutation probability 0.1", np.allclose(pct_muts_10, 0.1, atol=0.1)
print "Testing solutions valid         ", np.all([np.all(simple_mutate(x, 0.5) < 10) for i in xrange(N)])
print "Testing solutions valid         ", np.all([np.all(simple_mutate(x, 0.5) >= 0) for i in xrange(N)])

Testing mutation probability 0.5 True
Testing mutation probability 0.1 True
Testing solutions valid          True
Testing solutions valid          True


# Ejercicio 3:

### <font style="color:red">1.A) Realiza una función que dados dos vectores $v_1$ y $v_2$, produzca un nuevo vector $r$ de forma que:

- selecciona una posición aleatoria de $r$
- `r[pos:] = v1[pos:]`, donde $pos$ es la posición seleccionada en el punto anterior
- `r[:pos] = v2[:pos]`

Salida esperada (vectores aleatorios):


    v1 [85 55  9 24 71 80 94 26 36 24]
    v2 [90  8 63 74 71 55 44 84 61 27]
    r  [ 0 55  9 24 71 80 94 26 36 24]


In [7]:
def crossover(v1, v2):
    
    r = np.zeros(len(v1)).astype(int)
    ## TU CODIGO AQUI
    pos=np.random.randint(len(r))
    r[pos:] = v1[pos:]
    r[:pos] = v2[:pos]
    return r
    

### 1.B) inspecciona el resultado de tu código

In [8]:
v1 = np.random.randint(100, size=10)
v2 = np.random.randint(100, size=10)
r = crossover(v1,v2)
print "v1", v1
print "v2", v2
print "r ", r

v1 [60 81 87 50 81 52 88 35 41 25]
v2 [18 45 85 20 28 65  8 57 26 26]
r  [18 45 85 20 28 65  8 57 26 25]


### 1.C) verifica que el ejercicio está correcto

In [9]:
c = []
for i in range(100):
    v1 = np.random.randint(100, size=10)
    v2 = np.random.randint(100, size=10)
    r = crossover(v1,v2)
    tf = np.all(np.unique(list(np.where(v2==r)[0]) + list(np.where(v1==r)[0]))==np.arange(10))
    if not tf:
        print "--"
        print "v1", v1
        print "v2", v2
        print "r ", r
        print "l ", np.unique(list(np.where(v2==r)[0]) + list(np.where(v1==r)[0])), tf
    c.append(tf)
    
print "cross over correctos :: ", np.all(c)

cross over correctos ::  True


# Ejercicio 4:

### <font style="color:red">1.A) Realiza una función que dado un vector $x$, con 10 elementos enteros, entre 0 y 99 ambos incluidos, genere un nuevo vector $r$ de forma que la distancia euclideana entre ambos sea 2:

- selecciona una posición aleatoria de $r$
- `r[pos:] = v1[pos:]`, donde $pos$ es la posición seleccionada en el punto anterior
- `r[:pos] = v2[:pos]`

Salida esperada (vectores aleatorios):


    v1 [85 55  9 24 71 80 94 26 36 24]
    v2 [90  8 63 74 71 55 44 84 61 27]
    r  [ 0 55  9 24 71 80 94 26 36 24]


In [10]:
import numpy as np

def vecino(x):
    
    r = np.copy(x)
    pos=np.random.randint(len(r))
    r[pos]+=1
    
    return r

### 1.B) inspecciona el resultado de tu código

In [11]:
x = np.random.randint(10, size=10)
r = vecino(x)
print "x", x
print "r", r
print "distnacia euclideana", np.sqrt(np.sum((x-r)**2))

x [8 4 9 7 5 3 3 4 5 1]
r [9 4 9 7 5 3 3 4 5 1]
distnacia euclideana 1.0


### 1.C) verifica que el ejercicio está correcto

In [12]:
distancias = []
for i in xrange(100):
    x = np.random.randint(10, size=10)
    r = vecino(x)
    distancias.append(np.sqrt(np.sum((x-r)**2)))
    
print "todas las distancias son 2 ::", np.allclose(distancias, 2)

todas las distancias son 2 :: False
